### ISSUE TITLE
Possibility to add the percentile of the EPSS score ?

### ISSUE THREAD

**Issue by MrP1xel** [jgamblin/KEV_EPSS#1]
Hello,
the percentile is also available in the EPSS csv file (and it's an important metric), do you think it's possible to add this field to your generated csv file ?

Thanks

**Comment by jgamblin** [comment]
Good suggestion!  I added the EPSS Percentile to the CSV.

**Comment by MrP1xel** [comment]
Thanks for your prompt feedback and for the future change :)

**Comment by jgamblin** [comment]
You should see the change already. :)

**Comment by MrP1xel** [comment]
I confirm ! Thanks a lot !
