### ISSUE TITLE
Possibility to add vendor or product column in the exported csv file ?

### ISSUE THREAD

**Issue by MrP1xel** [jgamblin/KEV_EPSS#5]
Hello,
it will be usefull to get the vendor and product for each CVE (it's a data available in the KEV csv file)

Thanks,

Regards

**Comment by jgamblin** [comment]
https://github.com/jgamblin/KEV_EPSS/issues/5

**Comment by jgamblin** [comment]
Added Vendor and App to the file and updated repo to pull in recent CVSS data.
